#%RAML 1.0
title: Air Interface Adapter RESTful API
version: v1
baseUri: aiad:8080
mediaType:
  - application/json
protocols:
  - HTTP
types:
  Attenuator:
    type: object
    properties:
      attenuation: number
      frequency: string
  Error:
    type: string
  Aiad:
    type: object
    properties:
      frequencies: Attenuator[]

/aiad:
  get:
    responses:
      200:
        body:
          application/json:
            type: Aiad
            example: |
              {
                "frequencies" : [
                  {"frequency" : "800", "attenuation" : 10},
                  {"frequency" : "900", "attenuation" : 20},
                  {"frequency" : "1200", "attenuation" : 40},
                  {"frequency" : "1600", "attenuation" : 60},
                  {"frequency" : "2400", "attenuation" : 95}
                ]
              }
      500:
        body:
          application/json:
            type: Error
            example: |
              {
                "Error" : "Internal Server Error,
                            could not get data from Air Interface Adapter"
              }
  /{frequency}:
    get:
      responses:
        200:
          body:
            application/json:
              type: Attenuator
              example: |
                {
                  "frequency" : "800",
                  "attenuation" : 10
                }
        404:
          body:
            application/json:
               type: Error
               example: |
                {
                  "Error" : "Could not find url resource"
                }
        500:
          body:
            application/json:
               type: Error
               example: |
                {
                  "Error" : "Internal Server Error,
                              could not get data from Air Interface Adapter"
                }
    post:
      responses:
        204:
        400:
          body:
            application/json:
                type: Error
                example: |
                  {
                    "Error" : "Missing or invalid parameter"
                  }
        404:
          body:
            application/json:
                type: Error
                example: |
                  {
                    "Error" : "Could not find url resource"
                  }
        500:
          body:
            application/json:
                type: Error
                example: |
                  {
                    "Error" : "Internal Server Error,
                                could not get data from Air Interface Adapter"
                  }
